version: "3"

services:
  grafana:
    container_name: grafana
    labels:
      # SSL redirect requires a separate router (https://github.com/containous/traefik/issues/4688#issuecomment-477800500)
      - "traefik.http.routers.some-name.entryPoints=port80"
      - "traefik.http.routers.some-name.rule=host('metrics.silvertree.io')"
      - "traefik.http.middlewares.some-name-redirect.redirectScheme.scheme=https"
      - "traefik.http.middlewares.some-name-redirect.redirectScheme.permanent=true"
      - "traefik.http.routers.some-name.middlewares=some-name-redirect"
      # SSL endpoint
      - "traefik.http.routers.some-name-ssl.entryPoints=port443"
      - "traefik.http.routers.some-name-ssl.rule=host('metrics.silvertreelabs.io')"
      - "traefik.http.routers.some-name-ssl.tls=true"
      - "traefik.http.routers.some-name-ssl.tls.certResolver=le-ssl"
      - "traefik.http.routers.some-name-ssl.service=some-name-ssl"
      - "traefik.http.services.some-name-ssl.loadBalancer.server.port=3000"
    image: grafana/grafana-enterprise:latest # or probably any other version
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SERVER_ROOT_URL=https://metrics.silvertree.io
      - GF_SERVER_DOMAIN=metrics.silvertreelabs.io
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SECURITY_ADMIN_USER=Silvertreeadmin
      - GF_SECURITY_ADMIN_PASSWORD=Maverick123

  traefik:
    container_name: traefik
    image: traefik:v2.1.0
    ports:
      - "80:80"
      - "443:443"
      - "8086:8086"
      # expose port below only if you need access to the Traefik API
      #- "8080:8080"
    command:
      - "--log.level=DEBUG"
      #- "--api=true"
      - "--providers.docker=true"

      - "--entryPoints.port443.address=:443"
      - "--entryPoints.port80.address=:80"
      - "--entryPoints.port8086.address=:8086"

      - "--certificatesResolvers.le-ssl.acme.tlsChallenge=true"
      - "--certificatesResolvers.le-ssl.acme.email=rrishi2024@yahoo.com"
      - "--certificatesResolvers.le-ssl.acme.storage=/letsencrypt/acme.json"
    volumes:
      - traefik-data:/letsencrypt/
      - /var/run/docker.sock:/var/run/docker.sock

  influx:
    container_name: influxdb
    image: influxdb:latest # or any other recent version
    labels:
      # SSL endpoint
      - "traefik.http.routers.db-influx-ssl.entryPoints=port8086"
      - "traefik.http.routers.db-influx-ssl.rule=host('metrics.silvertreelabs.io')"
      - "traefik.http.routers.db-influx-ssl.tls=true"
      - "traefik.http.routers.db-influx-ssl.tls.certResolver=le-ssl"
      - "traefik.http.routers.db-influx-ssl.service=db-influx-ssl"
      - "traefik.http.services.db-influx-ssl.loadBalancer.server.port=8086"
    restart: always
    volumes:
      - influx-data:/var/lib/influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - INFLUXDB_HTTP_ENABLED=true
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - DOCKER_INFLUXDB_INIT_USERNAME=Silvertreeadmin
      - DOCKER_INFLUXDB_INIT_PASSWORD=Rooster123
      - DOCKER_INFLUXDB_INIT_ORG=Silvertree
      - DOCKER_INFLUXDB_INIT_BUCKET=firmware_size
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=1bbffa6e9788bfe6499230d4a0dc27061dae904c310f0cb81e20dbbb120329d5

volumes:
  traefik-data:
  grafana-data:
  influx-data:
